version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - server.js
    - package.json
    - dist/**/*
  base-directory: .
